### ISSUE TITLE
"Back to Safety" on certificate error dialog does not go back

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/morph-browser#116]
When browsing to a site with an SSL certificate error (try any of those on https://badssl.com), the certificate error dialog appears as expected:

![image](https://user-images.githubusercontent.com/21966173/49159282-bc954100-f2e9-11e8-9adf-84282d9977d2.png)

I tap "Back to safety".

### Expected behavior

The browser cancels navigation, then goes back to the site I was previously viewing.

### Actual behavior

The browser is left on a blank page. I must tap the Back button to continue browsing from where I left off.

**Comment by UniversalSuperBox** [comment]
Since I'm marking this as a "good first issue", I'm also going to offer some helpful hints and places to look in the code. Only a cursory understanding of QML is required to fix this issue, and you can ask in the Matrix room #ub_bootcamp:matrix.org for help.

## Hints to fix

The dialog is defined in [CertificateVerificationDialog.qml](https://github.com/ubports/morph-browser/blob/fb0acef99af01b72b428f13280d02bdf2de2ea6d/src/app/CertificateVerificationDialog.qml). There are two signals, `accept()` and `reject()`, which are sent from this dialog. In order to actually use a signal, you need to *connect* it to another signal or QML function. When a signal is connected to a function, the function is run when the signal is sent.

Actually showing the dialog on a certificate error is performed at: https://github.com/ubports/morph-browser/blob/1540ddc7664f7ecd818aa550c99105944d85e08e/src/app/WebViewImpl.qml#L217

A good solution will instruct `webview` to go back after *rejecting* the certificate error.

**Comment by balcy** [comment]
it might be good to take the canGoBack (http://doc.qt.io/qt-5/qml-qtwebview-webview.html#canGoBack-prop) property into account, because the insecure site could have been defined as homepage. (or being restored in session restore)

There might be one edge case, that could cause problems: If the previous page (with valid certificate) for some reason redirects to the broken page automatically, the user might end up in a loop where they can only close the browser or accept the navigation to the insecure page.

**Comment by balcy** [comment]
with https://github.com/ubports/morph-browser/pull/121 instead of a blank page an error page is shown

**Comment by balcy** [comment]
maybe we can add a Cancel button to the dialog, that just closes it (as the go back to safety button now does)
The back to safety button (if needed at all) should then only be visible if going back is possible.
For cases with only one embedded insecure resource on a page (as simulated with iframes here https://codepen.io/clime/pen/eoBGaY) the user should IMHO get the chance to stay on the page (which apart from the one part is secure) but still to reject the invalid certificate / insecure connection.

**Comment by UniversalSuperBox** [comment]
Does this work as you expect? https://github.com/ubports/morph-browser/pull/176

**Comment by balcy** [comment]
Hmm actually not quite, and after thinking about it I would not go back automatically at this point at all.
I think the handling of the timing here will be quite tricky: The navigation is deferred, and almost in the same moment of rejecting the certificate, the browser should go back.

Let's see why this issue appeared for the first time (first post):
_Actual behavior:
The browser is left on a blank page. I must tap the Back button to continue browsing from where I left off._

That is now no longer the case, because an error page now does appear instead.

Then it would be needed to handle the "embedded" certificate errors differently (e.g. not going back) than the normal ones, and the user would have different effects with the first page in a tab (error page will appear) or 2nd or higher page in the stack (browser will go back automatically)

 So why not changing the current green button "back to safety" to a "Cancel" button (standard color as the other cancel buttons) and leave the functionality as it is now ?
Does someone know if the original webbrowser-app navigate back in such a situation ?

I've made some tries with a three button dialog (proceed, back to safety, and cancel) like the following:
https://pastebin.ubuntu.com/p/MFYxvGPtxF/

And I've had the problem with going back twice there, too.

But in the end, does it really have to navigate back from the dialog ? What about including a back button on the error page instead ?

**Comment by cibersheep** [comment]
I think I like the later behaviour here:
 - tapping on a link shows the dialog: red [Proceed anyway] neutral grey [Cancel]
 - Tapping on Cancel, show the error page with a back button to previous page (if any)

If you decide to go with the three buttons dialog, remember that I would suggest that only [Proceed anyway] would be colored. The rest in neutral grey (if you set no color, the button takes a beautiful grey:) )

**Comment by jezek** [comment]
FP2 (2019-W32) - Fixed

After canceling untrusted certificate, error page with "Back to safety" button is shown (if there was a previous page), which takes us to previous page.
