### ISSUE TITLE
Page menu doesn't show

### ISSUE THREAD

**Issue by cibersheep** [ubports/morph-browser#117]
Device: m10 HD Xenial RC
Steps: Pull down menu and tap on «Page Menu»
Behaviour: Menu closes up

Expected: to pop up Page Menu

**Comment by balcy** [comment]
Hi that is because https://github.com/ubports/morph-browser/pull/89 is not yet merged to xenial. The page menu was only part of the PR. (in the latest version it is the "Zoom menu").
The Ubuntu touch updater will only update files that have changed since the last version, so in the current example "SettingsPage.qml" on your phone is still from the PR, and the other files from the xenial branch.
You either can reinstall the current debian package of the PR, or remove the PR and install the debian package of the xenial branch.
We should be able to merge it after https://github.com/ubports/morph-browser/issues/109 has been resolved (I've just made a PR for that, which will be probably applied after OTA6)

**Comment by cibersheep** [comment]
Oh, I see. Sorry about that :P
