### ISSUE TITLE
Some websites are not displayed.

### ISSUE THREAD

**Issue by Daniel20000522** [ubports/morph-browser#137]
Device: Nexus 5/hammerhead
Channel: RC
Build: 2018-W01 (2019-W01)

### **Steps to reproduce:**

- Go to [https://m.onet.pl](https://m.onet.pl) or [https://m.olx.pl](https://m.olx.pl) from your Morph Browser.
- You will see something like:
![screenshot20190105_214540991](https://user-images.githubusercontent.com/30577245/50729102-454a9c80-1134-11e9-847f-2510e8e58f1b.png)

**Comment by balcy** [comment]
hmm this one is interesting... The first url does work on my phone (also RC channel)

the second one seems to result in a circular / infinite redirect:
```
   https://m.olx.pl/      (start URL)
-> https://www.olx.pl/    (redirection)
-> https://www.olx.pl/i2/ (redirection)
-> https://m.olx.pl/      (redirection)
-> ...
```
in the end there is the error net::ERR_TOO_MANY_REDIRECTS

the question is, why this redirection occurs for morph, it might have to do something with the user agent. (not sure though)
It happens for me for both standard and desktop mode for morph.
In an oxide based browser the problem does not occur. (tested with Jade Diamond)

Note: that no error page, but rather the page in the screenshot is displayed, should be fixed with the merge of "xenial_-_loadfailed". Then you will see a "Network Error" page instead.

**Comment by Daniel20000522** [comment]
I do not know if it will help, but in the Github application after clicking the link, 2 pages load normally. So the problem is probably in Morph-Browser

**Comment by mihaelmilea** [comment]
olx.ro does the same for me - it doesn't work and displays the same blank page as above - but I made a webapp for olx.ro and that works!

**Comment by balcy** [comment]
ok interesting, do you know which user agent is set for the webapp ? Can you send the webapp or the contents of its desktop file ?

**Comment by mihaelmilea** [comment]
Sorry for the late reply. I don't remember setting up a user agent. I was surprized it just worked. Bellow is the desltop file:

[Desktop Entry]
Name=OLX
Comment=Webapp for olx.ro
Type=Application
Icon=/opt/click.ubuntu.com/.click/users/phablet/olx.mihael/olx.png
Exec=aa-exec-click -p olx.mihael_olx_0.1 -- webapp-container --webappUrlPatterns=https?://olx.ro/* http://olx.ro
Terminal=false
X-Ubuntu-Touch=true
X-Ubuntu-Splash-Color=#000000
Path=/opt/click.ubuntu.com/.click/users/phablet/olx.mihael
X-Ubuntu-Old-Icon=olx.png
X-Ubuntu-Application-ID=olx.mihael_olx_0.1
X-Ubuntu-UAL-Source-Desktop=/opt/click.ubuntu.com/.click/users/phablet/olx.mihael/olx.desktop

**Comment by frankthegerman** [comment]
I'm not sure whether this is going to help anyone but i am having the same problem on OPO. Nothing besides startpage is showing...

**Comment by Daniel20000522** [comment]
The problem in version 0.24+ubports+0~20190504104252 seems to be solved. I'm closing the problem.

**Comment by mihaelmilea** [comment]
The olx.ro still doesn't work: ERR_TOO_MANY_REDIRECTS

**Comment by Daniel20000522** [comment]
Have you updated the browser to the latest version? Enter in the terminal: apt list morph-browser

**Comment by mihaelmilea** [comment]
morph-browser/xenial 0.24+ubports+0~20190107202312.40~1.gbp402a5b armhf

**Comment by Daniel20000522** [comment]
Enter in terminal: sudo apt update && sudo apt list --upgradable && sudo apt upgrade morph-browser -y

**Comment by mihaelmilea** [comment]
I did the upgrade but still doesn't load olx.ro

**Comment by UniversalSuperBox** [comment]
@Daniel20000522, updates to Ubuntu Touch, including morph-browser, are delivered in the system image. Please don't recommend people run `apt` commands as this can desync an image with the software it is supposed to have on it. Rather, people can go to "Update settings" and change their release channel to go forward or backward in releases.

TOO_MANY_REDIRECTS is caused by a website trying to send you to too many different places before actually loading a page. This may be aggravated by our user agent, but it is an error on the website's part. Sometimes it can be solved by clearing your browser cache, but I went to the website after doing so and still got the error. Please contact the website's owner to let them know you're having trouble, you might be able to get them to fix the bug.

**Comment by mihaelmilea** [comment]
@UniversalSuperBox Thank you for your input! I appreciate all the work you guys are doing and, on top of that, you take your time to answer to people - this is all very, very kind and professional! Thanks again!
