### ISSUE TITLE
Very hard to switch between tabs in portrait mode FP2

### ISSUE THREAD

**Issue by osimmasgard** [ubports/morph-browser#150]
When I have multiple tabs open and want to switch between I am supposed to swipe from the bottom of the screen to get the list of open tabs. This action is very hard to succeed with and sometimes I have to swipe 10 times before the tab list is showing..

I am on 16.04/dev and not sure which version of Morph I have (how can I see this)

PS. Where is the log for Morph? Are all th apps logging to /var/log/syslog?

**Comment by balcy** [comment]
the one I know is in `/home/phablet/.cache/upstart/application-legacy-morph-browser-.log`
I think the version of the installed morph-browser package can be found with `apt list --installed | grep morph-browser`
Not sure why FP2 does behave differently here... I just have experience with Aquaris 4.5 so far.
maybe due to scaling the height of the swipe area is too small on this phone

**Comment by balcy** [comment]
would be interesting to see which devices are affected.

**Comment by osimmasgard** [comment]
About which morph version: morph-browser/now 0.24+ubports+0~20190130074333.41~1.gbp102e6c

The behaviour I described is not consistent for me so now I am starting to wonder if it has anything to do how I swipe and that I somehow have gotten better at swiping :)

Anyway, we can perhaps archive this thread and I can get back to it if I really can find it happening consistently or in certain situations.
