### ISSUE TITLE
Make tabs on tablet bigger

### ISSUE THREAD

**Issue by SaulNunez** [ubports/morph-browser#221]
On tablets (with the tabs on top) it seems like hitting a tab requires a bit of finesse. They are quite easily to cover with my whole finger specially as someone with fat fingers. I don't miss often but make for some odd UX. 

Can I suggest making the tabs have a bit more height, it can certainly help elder folks.

**Comment by JulianGro** [comment]
Yeah the tab size is pretty borderline. I would suggest a tab list like some other browsers use. Opera uses something like that on android for example. In Opera you can scroll on the tabs and a lot faster on the bar at the bottom which is also a nice touch. 
I personally don't have a problem with the current size of the tabs, but with moving to tabs which are not shown on the bar because there is to many options tabs. 

![Screenshot_2019-09-02-00-51-18-126_com opera browser](https://user-images.githubusercontent.com/11144627/64083209-03521480-cd1c-11e9-9768-4703345f9a9b.png)
![Screenshot_2019-09-02-00-51-22-778_com opera browser](https://user-images.githubusercontent.com/11144627/64083210-03521480-cd1c-11e9-829f-c7d73164b2d3.png)
