### ISSUE TITLE
Need confirmation about 'Clear all cookies'

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/morph-browser#276]
I have a doubt, so I ask you for confirmation: does 'clear all cookies' work actually (dev channel)?
Is this feature intended to delete morph-browser cookies ?
After performing 'clear all cookies', I still see the 'cookies' and 'cookies-journal' files in .local/share/morph-browser ? Is this normal?
Please tell me.
Thank you

**Comment by balcy** [comment]
I've tried it in dev channel on my phone now, and it works.
we use official method for QtWebEngine to delete the cookies now, that's why the file is not removed and even its size does not change. (the cookies are removed from the sqlite database)

You can do the following to verify:
copy the "Cookies" file before you delete the cookies to your PC (e.g. folder cookies-old), and after you clear the cookies again (e.g. folder cookies-new).
Then you can open them with `sqlitebrowser` and go to the Tab "Browser Data" of the table "cookies":
Before I deleted the cookies, I had entries in the table:

![image](https://user-images.githubusercontent.com/848115/71375628-37995b80-25bf-11ea-9dd9-df7775a734e9.png)

after it not:
![image](https://user-images.githubusercontent.com/848115/71375635-3ff19680-25bf-11ea-81dd-df768385f3c1.png)

Another test is logging in to a site that normally does remember your login (e.g. github).
After deleting the cookies, the page must ask you again for your password when you reload the page (the previous login is no longer active)

**Comment by balcy** [comment]
there is a command line way that works on the phone directly or with the downloaded file:
`sqlite3 -batch /home/phablet/.local/share/morph-browser/Cookies 'SELECT COUNT(*) FROM cookies'`
0
(the result is the number of cookies in the database and should be 0 after you clear them)

**Comment by gbdomubpkm** [comment]
Thank you. It's clear now. Cleaning the cookies leaves an empty cookie file: a bit desorienting for the non-specialist! 😉...Unlike browsing in private mode, which does not leave a cookie file in .local/share/morph-browser if there were none before browsing in private mode, and not the local storage or index.db folders (not cookies but traffic tracks) which can be present if non private browsing.
