### ISSUE TITLE
unable to set a bookmark

### ISSUE THREAD

**Issue by doniks** [ubports/morph-browser#3]
I think the old browser had a star in the url bar. that workflow worked nicely for me. the star is not present in the new one and I can't find any other way to bookmark either

**Comment by doniks** [comment]
Today the behavior seems a bit differen, so maybe reproduction is a bit random?!
* I do see the star on duckduckgo.com and github.com and can set bookmarks 
* when I go to forums.ubports.com, I see the star for a split second then it disappears

**Comment by doniks** [comment]
oh, and after setting those two bookmarks, I could open a new tab, be presented with the list of home+two bokmarks, and could navigate there.

then I closed the browser, reopend,  now the bookmarks are gone and I only see home.

in addition, when I tap on the menu,top right, then bookmarks, I see an empty screen. when I swipe up from bottom and open new tab I do see the (temporary) list of bookmarks

**Comment by advocatux** [comment]
To see the bookmarks you need to press "bookmarks" and then "new tab", at the bottom right hand side. 

That is not the desired behaviour obviously, but is not a "temporary list" but a permanent one for me.

EDIT:
- @doniks is right, is "temporary" and not "permanent" as I thought.
- Screenshot deleted because it doesn't make sense now

**Comment by ruedigerkupper** [comment]
Confirmed on hammerhead.

**Comment by doniks** [comment]
I can set bookmarks ok and I see them alright on the new tab page
