### ISSUE TITLE
morph branches

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#354]
Hi @mariogrip  and @UniversalSuperBox 

There are `xenial_-_edge` and `xenial_-_edge_-_pine` branches:

`xenial_-_edge` seems to have no changes (some commits behind xenial), and `xenial_-_edge_-_pine` does have the following two changes: https://github.com/ubports/morph-browser/compare/xenial_-_edge_-_pine

Do we need the branches and if yes should we rebase / fast forward them to xenial ? It looks like people on the edge channel would not receive the latest update of morph otherwise.

**Comment by balcy** [comment]
see https://github.com/ubports/morph-browser/issues/347

**Comment by UniversalSuperBox** [comment]
Yes, apologies. we need to manually rebase `xenial_-_edge_-_pine` from `xenial` when there are updates. That's because the Pine devices need https://github.com/ubports/morph-browser/commit/234c98f87289b17261c4acfd710734e860e97204 because https://github.com/ubports/ubuntu-touch/issues/1320

I've rebased xenial_-_edge_-_pine on xenial now.
