### ISSUE TITLE
Media stops playing when browser is not in foreground

### ISSUE THREAD

**Issue by likeadragonmaid** [ubports/morph-browser#385]
Media pauses/ stops when:

1. Browser is in background
2. Device is locked
3. Device is suspend/ sleep

I am using this image: https://ci.ubports.com/job/Device%20Compatibility%20Images/job/halium-generic_arm64/

**Comment by nanu-c** [comment]
That is intended. You need to use a tool to prevent app suspension: https://open-store.io/app/ut-tweak-tool.sverzegnassi

Did you play a podcast? Or do you want to play music?

**Comment by likeadragonmaid** [comment]
It works with ut tweak. Why is this a default behavior, shouldn't be browser excluded from this policy?

**Comment by mateosalta** [comment]
this helps with battery - otherwise you could have a repeating ad playing and the device would never sleep.

also this helps prevent spying - all apps are disallowed backgrounding unless they have the specific exception or permission
There is a media hub to specifically route sound - but this needs re-implementation for the browser to work with this
