### ISSUE TITLE
On Pro 5 Morph is verry small

### ISSUE THREAD

**Issue by ghost** [ubports/morph-browser#45]
- Device Pro 5
- Ubuntu Touch RC 2018-W41

Morph browser is verry small on a Pro 5.

Screenshots examples:

https://ibb.co/cc7sw9
https://ibb.co/giFO3p

**Comment by tomoqv** [comment]
Same for me on Pro 5. Looks fine in webapps (except a white line at the top). Morph browser looks OK on the M10 FHD.

**Comment by balcy** [comment]
I have a zoom feature (page- and configuration wise) in the pipeline, just waiting for my other PR to be merged first... 
Maybe there are users who prefer bigger or smaller content, so configurable zoom factor would be a good thing IMHO. (Additionally to the scaling done by QT itself, e.g. for texts and images)
[edit: the actual issue here seems to be a scaling issue of the app, not a problem with the zoom, the zoom itself would only affect the grey part in the screenshot, so a bit off topic here : ) ]

**Comment by mariogrip** [comment]
Fixed by https://github.com/ubports/qtubuntu/pull/8
