### ISSUE TITLE
Strange "out of focus"

### ISSUE THREAD

**Issue by FlavioMala** [ubports/morph-browser#450]
Device BQ E5
Ch dev.
Build/revision ? (since 1/2 months)

See here:
https://github.com/ubports/ubuntu-touch/issues/1647#issuecomment-764656723
If possible I will post screenshots here

**Comment by kugiigi** [comment]
It would be better if you can elaborate more and post a screenshot :)

**Comment by FlavioMala** [comment]
Yes.... I'm waiting for it "to happen", but since (a few days) docviewer and Pdfjsviewer no longer work well I mainly use the PC for downloads (with Sturm there are strange page jumps and with Libertine programs it is a stress: very small icons and buttons - for descktop- make it difficult, if not impossible, to use on a 5” screen!)

**Comment by FlavioMala** [comment]
I got it!
I wasn't able to take a full screen screenshot (you don't have time: a second since bring it in front... it crashes), but with the side views you can see, if you look closely!

The browser download window (second from left) is normal here
![screenshot20210125_174814136](https://user-images.githubusercontent.com/50835740/105738733-a5892280-5f37-11eb-9587-4ff74083d9b4.png)

Here the download window is out of focus (look carefully) compared to the others (and respect before)
![screenshot20210125_174734433](https://user-images.githubusercontent.com/50835740/105738832-c18cc400-5f37-11eb-97bc-e1b704df791b.png)

...and if you click it ... the browser then resets.

**Comment by kugiigi** [comment]
I think I understand your issue now and seeing that your on E5 then I moat likely correct. The thing is E5 only have 1GB of RAM and the browser can be a memory hog. Since you open a file on the document viewer, the system focus is on the document viewer app and other apps in the background are candidates for killing to free up memory. So what happens is that the browser is killed so when you get back to it, it just reopens. This can happen on any app. Sadly, this is both a hardware issue and a software optimization issue.

**Comment by FlavioMala** [comment]
OK, all clear, it can be. Thanks!

**Comment by UniversalSuperBox** [comment]
Ubuntu Touch kills apps when too much memory is in use. When it does this, it creates a placeholder image from the last known state of the killed app and shows it in the app spread. When you tap on this placeholder, the app is started again.

This is expected behavior.
