### ISSUE TITLE
Morph doesn't store login credentials

### ISSUE THREAD

**Issue by tomoqv** [ubports/morph-browser#47]
Pro 5 and M10 FHD with RC-W41

Steps to reproduce:
1. Go to you url (e.g. Whatsapp or Home Assistant)
2. Log in
3. Close the browser
4. Open the browser and go to the url again

Expected behaviour:
Still being logged in to the url in question.

Actual behaviour:
Morph browser asks for login credentials again.

**Comment by YougoCodes** [comment]
**device:** Fairphone 2
**os:** Ubntu Touch 16.04/rc (2018-W41)

same as above, only tested Whatsapp Web

1. use a webapp or the Morph browser to load web.whatsapp.com. 
2. scan the QR code with a device running whatsapp app. 
3. whatsapp web is logged in and functional
4. close the browser or webapp
5. use a webapp or the Morph browser to load web.whatsapp.com. 

**expected behavior:**
whatsapp web is logged in and functional

**actual behavior:**
whatsapp web shows the login page with the qr code

willing to supply logs, tweak settings and test .click apps

**Comment by mariogrip** [comment]
Should be fixed by: https://github.com/ubports/morph-browser/commit/02fffeb661abb13d3f5c7d5f1559e3790b1fd1a0 It should be in devel, Please test :)

**Comment by YougoCodes** [comment]
@mariogrip is this available in a .click or do i need the dev channel (or wait until rc updates)?

**Comment by mariogrip** [comment]
@YougoCodes you would need dev channel, but we will push a new rc later today.

**Comment by YougoCodes** [comment]
great, thanks :-)

**Comment by mymike00** [comment]
> but we will push a new rc later today.

@mariogrip where are you going to do that? I don't see any news at [system-image](http://system-image.ubports.com/ubports-touch/16.04/rc/hammerhead/)
