### ISSUE TITLE
Cannot copy current URL

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/morph-browser#64]
There seems to be no way of copying the current URL. I can mark the text (light blue background), but then I find not way of copying. The familiar long-press does not do anything in the URL bar...

Second, I tried the „share link“ option from the burger menu. It shows a selection of apps to share with, but nothing happens when I select one.

**Comment by balcy** [comment]
the second one is solved by now: https://github.com/ubports/morph-browser/issues/51
with my current version the copy does work as well for the URL

**Comment by balcy** [comment]
please reopen if the issue is still present on RC or devel

**Comment by ghost** [comment]
device:Nexus 5
channel: RC 2018-W48
issue solved. Unable to reproduce

**Comment by andrisk-dev** [comment]
device: Nexus 5 
build: 2018-W48
Unable to reproduce - can copy url with long press context menu and also through browser menu - share (copy url to new message in messages app).

**Comment by Mraanderson** [comment]
Device: Nexus 5
Channel: RC 2018-W48
Unable to reproduce. Long press on URL presents Cut/Copy option. Cut worked and paste worked.

**Comment by MEstner** [comment]
In 2018-w48 m10 fhd
Copy do what it should. If i open a new tap and try to paste I can't.
If I am already on a  website and then try to paste the url it works as expected.

**Comment by ruedigerkupper** [comment]
I think this is (mostly) solved:
- the hamburger menu still has no item to copy the URL
- I can mark the current URL with a short tap and then do a long press to get an option menu and copy it. That seems to work, although it is not the combination I have come to expect. (That would be the exact opposite: long-press to mark, then short tap to get an option menu what to do with it, like copy the text.)
I don't know if I am somehow skewed in my expectation or if GUI habits have really changed so much over the years.
To be more specific: Isn't the agreed-on way of interacting with text:
 - the user indicates what peace of text she wants to interact with (this is done on the desktop with a right click, which acceptably translates into a long click on the touch interface)
- after that, the user selects from that menu what to do (this is done on the desktop with a left click, which acceptably translates into a short click on the touch interface)

So the expected (and trained) combination is "long-press-then-tap", which fails. What works is "tap-then-long-press", which feels awkward.
Am I somehow skewed, or has this this been just confused in this context?

**Comment by balcy** [comment]
thank you for the observations and suggestions !
In fact the long press / right click does not trigger any action currently [edit: if done without selecting text first], we could create a dialog so that the user can paste (like paste and go) or copy the current url quickly without selecting the text first.

I found an interesting change of the default behavior of browser address fields:
With a current firefox (60.4) with a normal click to the address bar, not all text is selected and the cursor is just at the position you clicked.
Firefox 52.9 still had the effect, that a click into the address bar selcted the whole url automatically.
Chromium 72.0 still does select the whole URL though...

About the hamburger menu: The problem is that on my phone it already takes up all the available space, so would you mind adding the "copy current URL" to the very bottom ? Otherwise the Zoom menu would be hard to find I guess. Or we have to merge some of the items, e.g. "New" that opens a dialog for "New Window", "New private window", "New Tab"
