### ISSUE TITLE
Cannot download from Nextcloud

### ISSUE THREAD

**Issue by doniks** [ubports/morph-browser#7]
Repro:
Click on: https://nc.ubports.com/s/97D8BCsznfKX6AZ
(as linked here: https://forums.ubports.com/topic/1291/install-browser-ng-for-qtwebengine-goodness/24 )

Expected:
Starts downloading the ".click" package from there

Actual:
Nothing seems to happen

Note:
that link didn't really work in the old browser either. It failed in a subtly different way, but it failed.

**Comment by ernesst** [comment]
Was related to the hub-content, from what i remembered.
To download from nexclout you have to use the app in the openstore.

**Comment by doniks** [comment]
@ernesst I didn't fully get what you meant, but anyway ...

.... I just checked the link again and it doesn't download on my android phone either so .... whatever ... let's focus on stuff that matters. I'm closing this

**Comment by ernesst** [comment]
To be more clear, the Nextcloud server authentification is not carry from the browser to the hub content managing the download. So the hub-content cannot identify himself against the serveur thus doesn't get the access. (something like that). 
Mateo salta developped a webapp allowing you to download and upload from your nextcloud serveur.

So this issue is a hole between browser and hub content.

**Comment by mateosalta** [comment]
@bhdouglass developed the parts that made downloading possible :) but yeah, sometime I think this should be something to fix for the browser, as there are a few other sites with similar problems.

**Comment by bhdouglass** [comment]
If the browser could forward headers/cookies/etc to the download manager that could fix this issue (which is essentially what download interceptor does for the nextcloud webapp).
