### ISSUE TITLE
All tabs but current lose context

### ISSUE THREAD

**Issue by vandys** [ubports/morph-browser#99]
On dev, updated to 703, and Morph has returned to an early behavior where it maintains browser
context for only the current tab.  I can have two tabs, but I can clearly see it reload the content
afresh when I switch to the other tab.  This is on a freshly booted phone, nothing else competing for memory.

**Comment by balcy** [comment]
yes before https://github.com/ubports/morph-browser/pull/96 no tabs could be unloaded (even if they were closed)
On my phone (Aquaris 4.5) even with only one tab and no other apps open, I see `qml: System low on memory, but unable to pick a tab to unload` the whole time (and background tabs are always unloaded as you describe)
The calculation of free memory in morph-browser.qml might be inaccurate
`
var freeMemRatio = (MemInfo.total > 0) ? (MemInfo.free / MemInfo.total) : 1.0
 // Under that threshold, available memory is considered "low", and the
 // browser is going to try and free up memory from unused tabs. This
 // value was chosen empirically, it is subject to change to better
 // reflect what a system under memory pressure might look like.
 var lowOnMemory = (freeMemRatio < 0.2)
`
-> the ratio of 20% is the threshold
Up to now it always tried to unload tabs too, but because of an error (see mentioned issue / PR) the unload could not finish.

**Comment by balcy** [comment]
should we change the value to 0.15 or 0.1 perhaps ?

**Comment by vandys** [comment]
You may want to look at "avail" as distinct from "free".  A default Linux kernel tries to use would-be
idle memory to cache content, but that shouldn't make the browser leap to low memory behavior.
It isn't the end of the world to have Linux sweep through its less used pages and reclaim memory, and certainly preferable
to having a browser which doesn't support background tabs!

**Comment by UniversalSuperBox** [comment]
Looks like it's a misnomer: https://github.com/ubports/morph-browser/blob/65859e538d52281cc04c5a6554c403038b0f2389/src/app/meminfo.cpp#L124

`MemInfo.free` is actually the available RAM in the system.

**Comment by tjrhodes** [comment]
Device: FP2
System Build: 2018-W48

With 2 or more tabs open the background tabs are always unloaded for me. Only the active tab retains state.

**Comment by balcy** [comment]
yes, the same for me on BQ Aquaris 4.5, maybe we should still lower the threshold value ?

**Comment by vandys** [comment]
> maybe we should still lower the threshold value ?

You should check "free -h" from a shell, and if "avail" is a moderately large number, then you
may need to revisit the browser's free memory calculation rather than just lower that
threshold.  The latest builds have certainly fixed it for my on my Nexus 5.

**Comment by UniversalSuperBox** [comment]
The Nexus 5 sits at around 700MB of memory used at idle, I'm sure the same is true on other devices. Letting the browser keep things open when less than 20% of memory is available will cause the low-memory killer to kill unity8 far too often. We already [removed an important protection against that](https://github.com/ubports/ubuntu-app-launch/commit/68d120c867d4e78910a8181414efc52094c74e90), so I'm not comfortable decreasing the threshold.

**Comment by andrisk-dev** [comment]
Device: nexus 5
Build:  2018-W48

The tabs seems to retain state with three tabs opened. However previously hidden tabs does not show content on the tab selection screen.

**Comment by UniversalSuperBox** [comment]
@Andrissk, that seems like a different issue. Could you file another bug for the tab content?

**Comment by andrisk-dev** [comment]
> @Andrissk, that seems like a different issue. Could you file another bug for the tab content?

Ok, I have created new bug report - #972.

**Comment by MEstner** [comment]
In 2018-w48 for m10 fhd
The tabs only reload if the browser was closed and you go to the tab for the first time.
After this the tabs do not reload again.
